### ISSUE TITLE
ob run ignores css changes

### ISSUE THREAD

**Issue by eskimor** [obsidiansystems/obelisk#295]
ob run no longer serves the most recent css. I am pretty sure it used to do that, meaning:

- I change a css file in static
- I press F5 in browser
- I can see my changes.

That used to work (I am almost entirely certain, because I remember how cool I found that), but does not anymore. I have to kill ob run and start it again to see my changes.

**Comment by eskimor** [comment]
I guess this might have been fixed by: https://github.com/obsidiansystems/obelisk/commit/8e93cf384f27566e7a9e6c3f9691c50d77797dab

Going to verify.

**Comment by elgusy** [comment]
This still does not work, at least with the versions posted in readme. Any solution meanwhile?

**Comment by luigy** [comment]
@elgusy I tested this in 61dce9bee472a250195f2b43ee0dee31986043f5 and I'm getting it to pick up changes https://cloudup.com/ceOEosXj6qy
Any repro steps to trigger what you're seeing?
