### ISSUE TITLE
Can't find documentation for reflex

### ISSUE THREAD

**Issue by MazeChaZer** [obsidiansystems/obelisk#746]
I just created a new project using `ob init` and running `ob doc reflex` inside of it doesn't show me the path to the documentation:

```
./.obelisk/impl: command not cached, building ...
DONE Built on ./.obelisk/impl [command]
No valid, buildable packages found
```
I'm not exactly sure on what obelisk commit I am but I completely reinstalled obelisk a few days ago from the master so it can't be that old. My OS is Arch Linux.

Steps to reproduce:

```
$ mkdir foo
$ cd foo/
$ ob init
$ ob doc reflex
```

The `github.json`:

```
{
  "owner": "obsidiansystems",
  "repo": "obelisk",
  "branch": "master",
  "private": false,
  "rev": "3db33c4cf101999c7affb9c7b57f5e602cef4850",
  "sha256": "1shk8yy5pbakcw8aq6b8s3g2xblzf24l78mq0ca0asnvifnp83yb"
}
```

It **works** however when I checkout your calculator tutorial and run `ob doc reflex` there. The `github.json` in there for which it works:

```
{
  "owner": "obsidiansystems",
  "repo": "obelisk",
  "branch": "ls-reflex-frp",
  "rev": "50a5b9e0da7986de0f885575ab302ca05dc793ac",
  "sha256": "0qx74sl710zd50zgccyn8y4c37d5lj3xhh7ckicjvhy5kbk12bps"
}
```

So it could be a regression?

**Comment by tomsmalley** [comment]
This should be fixed by https://github.com/obsidiansystems/obelisk/pull/722

**Comment by MazeChaZer** [comment]
I installed Obelisk with `nix-env -f https://github.com/obsidiansystems/obelisk/archive/develop.tar.gz -iA command` to test this and it's still broken for me.

**Comment by tomsmalley** [comment]
It seems likely that the project you're testing this in actually points to `master` (see `.obelisk/impl`). It doesn't matter which version of `ob` the tool you have installed - it will "hand off" to the project obelisk when running commands inside an obelisk project.

If you try initialising a new project like `ob init --branch develop`, you should see that this command works.

**Comment by MazeChaZer** [comment]
Yes, with your command it works. Thanks for helping me!
